export const QuestionConstants = {
  FETCH_ALL_BEGIN: 'Question.FETCH_ALL_BEGIN',
  FETCH_ALL_SUCCESS: 'Question.FETCH_ALL_SUCCESS',
  FETCH_ALL_FAILURE: 'Question.FETCH_ALL_FAILURE',
  ANSWER_BEGIN: 'Question.ANSWER_BEGIN',
  ANSWER_SUCCESS: 'Question.ANSWER_SUCCESS'
};

export const PartyConstants = {
  FETCH_ALL_BEGIN: 'Party.FETCH_ALL_BEGIN',
  FETCH_ALL_SUCCESS: 'Party.FETCH_ALL_SUCCESS',
  FETCH_ALL_FAILURE: 'Party.FETCH_ALL_FAILURE'
};
